const chalk = require("chalk")
const validator = require("validator")
console.log(chalk.red.inverse('Hellow World'))
const res = validator.isEmail("souradip@gmail.com")
console.log(res ? chalk.green.inverse(res) : chalk.red.inverse(res))